app/models/Proveedores.py
from app import db

class Proveedores(db.Model):
    __tablename__ = 'proveedor'
    idProveedores = db.Column(db.Integer, primary_key=True)
    nombreProveedores = db.Column(db.String(255), nullable=False)
    direccionProveedores = db.Column(db.String(255), nullable=False)
    telefonoProveedores = db.Column(db.String(255), nullable=False)
    correoProveedores = db.Column(db.String(255), nullable=False)
    

app/routes/Auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from app.models.Clientes import Clientes
from app.models.Empleados import Empleados

bp = Blueprint('Auth', __name__)
@bp.route('/', methods=['GET', 'POST'])
def login():
    global tipodeusuario
    if request.method == 'POST':
        nombre = request.form['nombre']
        contrasena = request.form['contrasena']
        
        empleados = Empleados.query.filter_by(nombreEmpleados=nombre, contrasenaEmpleados=contrasena).first()
    
        if empleados:
            login_user(empleados)
            flash("Login successful!", "success")
            tipodeusuario = 1
            print("Entra a empleado ", current_user.idEmpleados)
            return redirect(url_for('Empleados.index'))
        clientes = Clientes.query.filter_by(nombreClientes=nombre, contrasenaClientes=contrasena).first()

        if clientes:
            login_user(clientes)
            print(current_user.nombreClientes)            
            tipodeusuario = 0
            print("Entra a Cliente", current_user.idClientes)
            return redirect(url_for('Productos1.index'))
        flash('Invalid credentials. Please try again.','danger')
    return render_template("Auth/login.html")

@bp.route('/Iniciar')
@login_required
def Iniciar():
     return redirect(url_for('Productos1.index'))


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return render_template("Auth/login.html")

app/routes/Proveedores_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.Proveedores import Proveedores
from app import db

bp = Blueprint('Proveedores', __name__)

@bp.route('/Proveedores')
def index():
    data = Proveedores.query.all()
    # Proveedores_list = [Proveedores.to_dict() for book in data]
    # return jsonify(Proveedores_list)
    return render_template('Proveedores/index.html', data=data)

@bp.route('/Proveedores/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombreProveedores = request.form['nombreProveedores']
        direccionProveedores = request.form['direccionProveedores']
        telefonoProveedores = request.form['telefonoProveedores']
        correoProveedores = request.form['correoProveedores']
        
        new_Proveedores = Proveedores(nombreProveedores=nombreProveedores, direccionProveedores=direccionProveedores, telefonoProveedores=telefonoProveedores, correoProveedores=correoProveedores)
        db.session.add(new_Proveedores)
        db.session.commit()
        
        return redirect(url_for('Proveedores.index'))

    return render_template('Proveedores/add.html')

@bp.route('/Proveedores/edit/<int:idProveedores>', methods=['GET', 'POST'])
def edit(idProveedores):
    proveedor = Proveedores.query.get_or_404(idProveedores)

    if request.method == 'POST':
        proveedor.nombreProveedores = request.form['nombreProveedores']
        proveedor.direccionProveedores = request.form['direccionProveedores']
        proveedor.telefonoProveedores = request.form['telefonoProveedores']
        proveedor.correoProveedores = request.form['correoProveedores']
       
        db.session.commit()
        return redirect(url_for('Proveedores.index'))

    return render_template('Proveedores/edit.html', proveedor=proveedor)
    

@bp.route('/Proveedores/delete/<int:idProveedores>')
def delete(idProveedores):
    proveedores = Proveedores.query.get_or_404(idProveedores)
    
    db.session.delete(proveedores)
    db.session.commit()

    return redirect(url_for('Proveedores.index'))

app/templates/Proveedores/add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styleProveedores.css') }}">
    <title>Agregar Proveedor</title>
</head>

<body>
    <h1>Agregar Proveedor</h1>
    <form action="{{ url_for('Proveedores.add') }}" method="post">
        <div class="mb-3">
            <label for="exampleInputNombreProveedores" class="form-label">Nombre Proveedores</label>
            <input type="text" name="nombreProveedores" class="form-control" id="exampleInputNombreProveedores"
                aria-describedby="nombreProveedoresHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputDireccion1" class="form-label">Direccion Proveedores</label>
            <input type="text" name="direccionProveedores" class="form-control" id="exampleInputDireccion1">
        </div>
        <div class="mb-3">
            <label for="exampleInputTelefono1" class="form-label">Telefono Proveedores</label>
            <input type="text" name="telefonoProveedores" class="form-control" id="exampleInputTelefono1">
        </div>
        <div class="mb-3">
            <label for="exampleInputCorreo1" class="form-label">Correo Proveedores</label>
            <input type="text" name="correoProveedores" class="form-control" id="exampleInputCorreo1">
        </div>
        <button type="submit" class="btn btn-primary">Agregar Proveedor</button>
    </form>
</body>

</html>

app/templates/Proveedores/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styleProveedores.css') }}">
    <title>Editar Proveedores</title>
</head>

<body>
    <h1>Editar Proveedores</h1>
    <form action="{{ url_for('Proveedores.edit', idProveedores=proveedor.idProveedores) }}" method="post">
        <div class="mb-3">
            <label for="exampleInputNombreClientes" class="form-label">Nombre Proveedores</label>
            <input type="text" id="nombreProveedores" name="nombreProveedores" class="form-control"
                value="{{ proveedor.nombreProveedores }}" id="exampleInputNombreProveedores"
                aria-describedby="nombreProveedoresHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputDireccion1" class="form-label">Direccion Proveedores</label>
            <input type="text" id="direccionProveedores" name="direccionProveedores" class="form-control"
                value="{{ proveedor.direccionProveedores }}" id="exampleInputDireccion1">
        </div>
        <div class="mb-3">
            <label for="exampleInputTelefono1" class="form-label">Telefono Proveedores</label>
            <input type="text" id="telefonoProveedores" name="telefonoProveedores" class="form-control"
                value="{{ proveedor.telefonoProveedores }}" id="exampleInputTelefono1">
        </div>
        <div class="mb-3">
            <label for="exampleInputCorreo1" class="form-label">Correo Proveedores</label>
            <input type="text" id="correoProveedores" name="correoClientes" class="form-control"
                value="{{ proveedor.correoProveedores }}" id="exampleInputCorreo1">
        </div>
        <button type="submit" class="btn btn-primary">Actualizar Proveedor</button>
    </form>
</body>

</html>

app/templates/Proveedores/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <script src="{{ url_for('static', filename='boot/js/jquery-3.7.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='boot/js/bootstrap.bundle.js') }}"></script>
    <title>Proveedores</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 1200px;
            margin: auto;
            padding: 20px;
        }

        h1 {
            margin-bottom: 20px;
            color: #007bff;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #0ccbdf;
            color: #fff;
            font-weight: bold;
        }

        td {
            color: #333;
        }

        td a {
            color: #007bff;
            margin-right: 10px;
            transition: color 0.3s ease;
        }

        td a:hover {
            text-decoration: none;
            color: #0056b3;
        }

        .dropdown {
            display: inline-block;
            margin-bottom: 20px;
        }

        .dropdown-toggle {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
        }

        .dropdown-menu {
            min-width: 200px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .dropdown-item {
            color: #333;
            padding: 10px 20px;
            transition: background-color 0.3s ease;
        }

        .dropdown-item:hover {
            background-color: #0ccbdf;
            color: #fff;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Lista de Proveedores</h1>
        <div class="dropdown">
            <button class="btn btn-info dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Tablas
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{ url_for('Empleados.index') }}">Empleados</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Productos.index') }}">Productos</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Clientes.index') }}">Clientes</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Compras.index') }}">Compras</a></li>
                <li><a class="dropdown-item" href="{{ url_for('DetalleCompras.index') }}">DetalleCompras</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Ventas.index') }}">Ventas</a></li>
                <li><a class="dropdown-item" href="{{ url_for('DetalleVentas.index') }}">DetalleVentas</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Proveedores.index') }}">Proveedores</a></li>
                <li>
                    <form class="d-flex" role="searc
                h" action="{{ url_for('Auth.logout') }}">
                        <button class="btn btn-outline-info" type="submit">Cerrar Sesión</button>
                    </form>
                </li>
            </ul>
        </div>


        <table>
            <tr>
                <th>Id Proveedores</th>
                <th>Nombre Proveedores</th>
                <th>Direccion Proveedores</th>
                <th>Telefono Proveedores</th>
                <th>Correo Proveedores</th>
                <th>Acciones</th>
            </tr>
            {% for Proveedores in data %}
            <tr>
                <td>{{ Proveedores.idProveedores }}</td>
                <td>{{ Proveedores.nombreProveedores }}</td>
                <td>{{ Proveedores.direccionProveedores }}</td>
                <td>{{ Proveedores.telefonoProveedores }}</td>
                <td>{{ Proveedores.correoProveedores }}</td>
                <td>
                    <a href="{{ url_for('Proveedores.edit', idProveedores=Proveedores.idProveedores) }}"
                        class="btn btn-warning">Editar</a>
                    <a href="{{ url_for('Proveedores.delete', idProveedores=Proveedores.idProveedores) }}"
                        class="btn btn-danger">Eliminar</a>
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
            {% endfor %}
        </table>

    </div>
</body>

</html>