app/models/Productos.py
from app import db

class Productos(db.Model):
    __tablename__ = 'producto'
    idProductos = db.Column(db.Integer, primary_key=True)
    nombreProductos = db.Column(db.String(255), nullable=False)
    descripcionProductos = db.Column(db.String(255), nullable=False)
    precioProductos = db.Column(db.Integer, nullable=False)
    fechaCaducidadProductos = db.Column(db.Date, nullable=False)
    nombreImagen = db.Column(db.String(255), nullable=False, default="sinfoto.jpg")
    ventas = db.relationship("Ventas", secondary="detalle_venta", back_populates="productos")

app/routes/Auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from app.models.Clientes import Clientes
from app.models.Empleados import Empleados

bp = Blueprint('Auth', __name__)
@bp.route('/', methods=['GET', 'POST'])
def login():
    global tipodeusuario
    if request.method == 'POST':
        nombre = request.form['nombre']
        contrasena = request.form['contrasena']
        
        empleados = Empleados.query.filter_by(nombreEmpleados=nombre, contrasenaEmpleados=contrasena).first()
    
        if empleados:
            login_user(empleados)
            flash("Login successful!", "success")
            tipodeusuario = 1
            print("Entra a empleado ", current_user.idEmpleados)
            return redirect(url_for('Empleados.index'))
        clientes = Clientes.query.filter_by(nombreClientes=nombre, contrasenaClientes=contrasena).first()

        if clientes:
            login_user(clientes)
            print(current_user.nombreClientes)            
            tipodeusuario = 0
            print("Entra a Cliente", current_user.idClientes)
            return redirect(url_for('Productos1.index'))
        flash('Invalid credentials. Please try again.','danger')
    return render_template("Auth/login.html")

@bp.route('/Iniciar')
@login_required
def Iniciar():
     return redirect(url_for('Productos1.index'))


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return render_template("Auth/login.html")

app/routes/Carrito_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from app.models.Productos import Productos
from app.models.Carrito import Carrito
from app.models.Ventas import Ventas
from app.models.DetalleVentas import DetalleVentas
from flask_login import current_user
from app import db

bp = Blueprint('carritos', __name__)
carrito_ventas = Carrito()

@bp.route('/ListarCarrito')
def listar():
    items = carrito_ventas.getItems()
    return render_template('Productos/List.html', items=items)

@bp.route('/ListarProductos')
def index():
    productos = carrito_ventas
    return render_template('index.html', productos=productos)

@bp.route('/agregar/<int:id>', methods=['POST'])
def agregar_al_carrito(id):
    cantidad = int(request.form.get('cantidad', 1))
    carrito_ventas.agregar_producto(id, cantidad)
    
    return redirect(url_for
    
    ('Productos1.index'))
    #return "Entra a agregar corrito"

@bp.route('/realizar_compra')
def realizar_compra():
    total = carrito_ventas.calcular_total()
    suma = carrito_ventas.tamañoD()
    
    new_venta = Ventas(cantidadVentas=suma,idClientes=current_user.idClientes, total=total)
    db.session.add(new_venta)
    db.session.commit()

    factura = carrito_ventas.getItems()

    for producto in factura:

        
        producto2 = producto['producto']
        detalles = DetalleVentas(cantidadDetalle=producto['cantidad'], subTotalDetalle=producto2.precioProductos, idVentas=new_venta.idVentas, idProductos=producto2.idProductos)
        db.session.add(detalles)

    db.session.commit()
    detalle = DetalleVentas.query.filter_by(idVentas=new_venta.idVentas).all()

    return render_template('Carrito/realizar_Compra.html', detalles=detalle,new_venta=new_venta)

@bp.route('/generar_factura', methods=['POST'])
def generar_factura():
    total = carrito_ventas.calcular_total()
   
    # Aquí puedes almacenar la información en la base de datos (crear registros en Carrito y Factura)
    # y luego limpiar el carrito de compras
    carrito_ventas.carrito = []
    return render_template('Carrito/venta.html', total=total)

@bp.route('/itemscarrito', methods=['GET', 'POST'])
def tCarrito():
    a = carrito_ventas.tamañoD()
    print("Entra a carrito rutas", a)
    return f"Entra a carrito {carrito_ventas.tamañoD()}"

app/routes/Productos_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.Productos import Productos
from app.routes.Carrito_routes import carrito_ventas
from app import db
import os


bp = Blueprint('Productos', __name__)

@bp.route('/Productos')
def index():
    data = Productos.query.all()
    # Productos_list = [Productos.to_dict() for book in data]
    # return jsonify(Productos_list)
    return render_template('Productos/index.html', data=data,t=carrito_ventas.tamañoD())

@bp.route('/Productos/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombreProductos = request.form['nombreProductos']
        descripcionProductos = request.form['descripcionProductos']
        precioProductos = request.form['precioProductos']
        fechaCaducidadProductos = request.form['fechaCaducidadProductos']
        Imagen = request.files['nombreImagen']

        new_Productos = Productos(nombreProductos=nombreProductos, descripcionProductos=descripcionProductos, precioProductos=precioProductos, fechaCaducidadProductos=fechaCaducidadProductos, nombreImagen=Imagen.filename)
        guardarImagen(Imagen)   
        db.session.add(new_Productos)
        db.session.commit()
        
        return redirect(url_for('Productos.index'))

    return render_template('Productos/add.html')

@bp.route('/Productos/edit/<int:idProductos>', methods=['GET', 'POST'])
def edit(idProductos):
    producto = Productos.query.get_or_404(idProductos)

    if request.method == 'POST':
        producto.nombreProductos = request.form['nombreProductos']
        producto.descripcionProductos = request.form['descripcionProductos']
        producto.precioProductos = request.form['precioProductos']
        producto.fechaCaducidadProductos = request.form['fechaCaducidadProductos']
        
        db.session.commit()
        return redirect(url_for('Productos.index'))

    return render_template('Productos/edit.html', producto=producto)
    

@bp.route('/Productos/delete/<int:idProductos>')
def delete(idProductos):
    productos = Productos.query.get_or_404(idProductos)
    
    db.session.delete(productos)
    db.session.commit()
    return redirect(url_for('Productos.index'))


def guardarImagen(imagen):
    from run import app
    carpetaDestino = os.path.join(app.root_path, "static", "imagenes")
    imagen.save(os.path.join(carpetaDestino, imagen.filename))


def eliminar(idProductos):
    from run import app
    producto = Productos.query.get_or_404(idProductos)
    ruta_imagen = os.path.join(app.root_path, "static", "imagenes", producto.nombreImagen)

    if os.path.exists(ruta_imagen):
        os.remove(ruta_imagen)

app/templates/Productos/List.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styleProductos.css') }}">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        h1 {
            color: black;
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #f5f5f5;
        }

        a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            margin-top: 20px;
            text-align: center;
        }

        a:hover {
            background-color: #0056b3;
        }
    </style>
    <title>Lista de Productos</title>
</head>

<body>
    <div>
        <h1>Carrito</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Descripcion</th>
                    <th>Precio</th>
                    <th>Fecha</th>
                    <th>Cantidad</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                    <tr>
                        <td>{{ item['producto'].nombreProductos }}</td>
                        <td>{{ item['producto'].descripcionProductos }}</td>
                        <td>{{ item['producto'].precioProductos }}</td>
                        <td>{{ item['producto'].fechaCaducidadProductos }}</td>
                        <td>{{ item['cantidad'] }}</td>
                        <td>
                            <!-- Agrega aquí el enlace para eliminar -->
                        </td>
                    </tr>
                {% endfor %}
               
            </tbody>
            
        </table>
        <a href="{{ url_for('carritos.realizar_compra') }}" class="btn btn-outline-info">Generar factura</a>
    </div>
</body>

</html>

app/templates/Productos/add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styleProductos.css') }}">
    <title>Agregar Productos</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            color: #495057;
            margin: 20px;
        }

        h1 {
            color: #007bff;
            text-align: center;
            margin-bottom: 30px;
        }
      
        form {
            max-width: 500px;
            margin: auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s, box-shadow 0.3s;
        }

        form:hover {
            transform: scale(1.03);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
        }

        .form-label {
            font-weight: bold;
            color: #333;
        }

        .form-control {
            margin-bottom: 15px;
            border-radius: 5px;
            border: 1px solid #ddd;
            padding: 8px;
        }

        .btn-primary {
            background-color: #007bff;
            border: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .btn-primary:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
    <h1>Agregar Productos</h1>
    <form action="{{ url_for('Productos.add') }}" method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label for="exampleInputNombreProdutos" class="form-label">Nombre Productos</label>
            <input type="text" name="nombreProductos" class="form-control" id="exampleInputNombreProductos"
                aria-describedby="nombreProductosHelp" required>
        </div>
        <div class="mb-3">
            <label for="exampleInputDescripcion1" class="form-label">Descripcion Productos</label>
            <input type="text" name="descripcionProductos" class="form-control" id="exampleInputDescripcion1"
                required>
        </div>
        <div class="mb-3">
            <label for="exampleInputPrecio1" class="form-label">Precio Productos</label>
            <input type="number" name="precioProductos" class="form-control" id="exampleInputPrecio1" required>
        </div>
        <div class="mb-3">
            <label for="exampleInputFecha1" class="form-label">Fecha Caducidad Productos</label>
            <input type="date" name="fechaCaducidadProductos" class="form-control" id="exampleInputFecha1" required>
        </div>
        <div class="mb-3">
            <label for="img" class="form-label">Imagen:</label>
            <input type="file" accept=".png, .jpg, .jpeg" name="nombreImagen" required>
        </div>

        <button type="submit" class="btn btn-primary">Agregar Productos</button>
    </form>
</body>

</html>

app/templates/Productos/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styleProductos.css') }}">
    <title>Editar Productos</title>
</head>
<body>
    <h1>Editar Productos</h1>
    <form action="{{ url_for('Productos.edit', idProductos=producto.idProductos) }}" method="post">
        <div class="mb-3">
            <label for="exampleInputNombreProductos" class="form-label">Nombre Productos</label>
            <input type="text" id="nombreProductos" name="nombreProductos" class="form-control"
              value="{{ producto.nombreProductos }}" id="exampleInputNombreProductos" aria-describedby="nombreProductosHelp">
          </div>
          <div class="mb-3">
            <label for="exampleInputDescripcion1" class="form-label">Descripcion Productos</label>
            <input type="text" id="descripcionProductos" name="descripcionProductos" class="form-control"
              value="{{ producto.descripcionProductos }}" id="exampleInputDescripcion1">
          </div>
          <div class="mb-3">
            <label for="exampleInputPrecio1" class="form-label">Precio Productos</label>
            <input type="int" id="precioProductos" name="precioProductos" class="form-control"
              value="{{ producto.precioProductos }}" id="exampleInputPrecio1">
          </div>
          <div class="mb-3">
            <label for="exampleInputFecha1" class="form-label">Fecha Caducidad Productos</label>
            <input type="date" id="fechaCaducidadProductos" name="fechaCaducidadProductos" class="form-control"
              value="{{ producto.fechaCaducidadProductos }}" id="exampleInputFecha1">
          </div>
          <button type="submit" class="btn btn-primary">Actualizar Producto</button>
    </form>
</body>
</html>

app/templates/Productos/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styleProductos.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="{{ url_for('static', filename='boot/js/jquery-3.7.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='boot/js/bootstrap.bundle.js') }}"></script>


    <title>Producto</title>
</head>

<body>
    <h1>Lista de Producto </h1>
    <div class="dropdown">
        <button class="btn btn-info dropdown-toggle" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Tablas
        </button>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('Productos1.index') }}">Ir a Productos</a></li>
            <li><a class="dropdown-item" href="{{ url_for('Productos.add') }}">Agregar Productos</a></li>
            <li><a class="dropdown-item" href="{{ url_for('Empleados.index') }}">Empleados</a></li>
            <li><a class="dropdown-item" href="{{ url_for('Productos.index') }}">Productos</a></li>
            <li><a class="dropdown-item" href="{{ url_for('Clientes.index') }}">Clientes</a></li>
            <li><a class="dropdown-item" href="{{ url_for('Compras.index') }}">Compras</a></li>
            <li><a class="dropdown-item" href="{{ url_for('DetalleCompras.index') }}">DetalleCompras</a></li>
            <li><a class="dropdown-item" href="{{ url_for('Ventas.index') }}">Ventas</a></li>
            <li><a class="dropdown-item" href="{{ url_for('DetalleVentas.index') }}">DetalleVentas</a></li>
            <li><a class="dropdown-item" href="{{ url_for('Proveedores.index') }}">Proveedores</a></li>
            <li>
                <form class="d-flex" role="searc
                h" action="{{ url_for('Auth.logout') }}">
                    <button class="btn btn-outline-info" type="submit">Cerrar Sesión</button>
                </form>
            </li>
        </ul>
    </div>
    <div>
       
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Id Productos</th>
                        <th scope="col">Nombre Productos</th>
                        <th scope="col">Descripcion Productos</th>
                        <th scope="col">Precio Productos</th>
                        <th scope="col">Fecha Caducidad Productos</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for Productos in data %}
                    <tr>
                        <td>{{ Productos.idProductos }}</td>
                        <td>{{ Productos.nombreProductos }}</td>
                        <td>{{ Productos.descripcionProductos }}</td>
                        <td>{{ Productos.precioProductos }}</td>
                        <td>{{ Productos.fechaCaducidadProductos }}</td>
                       
                        <td>
                            <div class="btn-group" role="group">
                                <a href="{{ url_for('Productos.edit', idProductos=Productos.idProductos) }}"
                                    class="btn btn-warning">Editar</a>
                                <a href="{{ url_for('Productos.delete', idProductos=Productos.idProductos) }}"
                                    class="btn btn-danger">Eliminar</a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
        
        

</body>

</html>