app/models/Clientes.py
from app import db
from flask_login import UserMixin

class Clientes(db.Model, UserMixin):
    __tablename__ = 'cliente'
    idClientes = db.Column(db.Integer, primary_key=True)
    nombreClientes = db.Column(db.String(255), nullable=False)
    direccionClientes = db.Column(db.String(255), nullable=False)
    telefonoClientes = db.Column(db.String(255), nullable=False)
    correoClientes = db.Column(db.String(255), nullable=False)
    contrasenaClientes = db.Column(db.String(255), nullable=False)
    ventas = db.relationship("Ventas", back_populates="clientes")
   
    def get_id(self):
        return str(self.idClientes)

app/routes/Auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from app.models.Clientes import Clientes
from app.models.Empleados import Empleados

bp = Blueprint('Auth', __name__)
@bp.route('/', methods=['GET', 'POST'])
def login():
    global tipodeusuario
    if request.method == 'POST':
        nombre = request.form['nombre']
        contrasena = request.form['contrasena']
        
        empleados = Empleados.query.filter_by(nombreEmpleados=nombre, contrasenaEmpleados=contrasena).first()
    
        if empleados:
            login_user(empleados)
            flash("Login successful!", "success")
            tipodeusuario = 1
            print("Entra a empleado ", current_user.idEmpleados)
            return redirect(url_for('Empleados.index'))
        clientes = Clientes.query.filter_by(nombreClientes=nombre, contrasenaClientes=contrasena).first()

        if clientes:
            login_user(clientes)
            print(current_user.nombreClientes)            
            tipodeusuario = 0
            print("Entra a Cliente", current_user.idClientes)
            return redirect(url_for('Productos1.index'))
        flash('Invalid credentials. Please try again.','danger')
    return render_template("Auth/login.html")

@bp.route('/Iniciar')
@login_required
def Iniciar():
     return redirect(url_for('Productos1.index'))


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return render_template("Auth/login.html")

app/routes/Clientes_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, Flask
from app.models.Clientes import Clientes
from flask_login import login_required
from app import db
app = Flask(__name__)

bp = Blueprint('Clientes', __name__)

@bp.route('/Clientes')
@login_required
def index():
    print("Entra a clientes")
    data = Clientes.query.all()
    print("Entra a clientes")

    # Clientes_list = [Clientes.to_dict() for book in data]
    # return jsonify(Clientes_list)
    return render_template('Clientes/index.html', data=data)

@bp.route('/Clientes/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombreClientes = request.form['nombreClientes']
        direccionClientes = request.form['direccionClientes']
        telefonoClientes = request.form['telefonoClientes']
        correoClientes = request.form['correoClientes']
        contrasenaClientes = request.form['contrasenaClientes']

        new_Clientes = Clientes(nombreClientes=nombreClientes, direccionClientes=direccionClientes, telefonoClientes=telefonoClientes, correoClientes=correoClientes, contrasenaClientes=contrasenaClientes)
        db.session.add(new_Clientes)
        db.session.commit()
        
        return redirect(url_for('Clientes.index'))

    return render_template('Clientes/add.html')

@bp.route('/Clientes/edit/<int:idClientes>', methods=['GET', 'POST'])
def edit(idClientes):
    cliente = Clientes.query.get_or_404(idClientes)

    if request.method == 'POST':
        cliente.nombreClientes = request.form['nombreClientes']
        cliente.direccionClientes = request.form['direccionClientes']
        cliente.telefonoClientes = request.form['telefonoClientes']
        cliente.correoClientes = request.form['correoClientes']
        cliente.contrasenaClientes = request.form['contrasenaClientes']

        db.session.commit()
        return redirect(url_for('Clientes.index'))

    return render_template('Clientes/edit.html', cliente=cliente)
    

@bp.route('/Clientes/delete/<int:idClientes>')
def delete(idClientes):
    clientes = Clientes.query.get_or_404(idClientes)
    
    db.session.delete(clientes)
    db.session.commit()

    return redirect(url_for('Clientes.index'))

app/templates/Clientes/add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <title>Agregar Clientes</title>
    <style>
        body {
            background-color: #f8f9fa;
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
        }

        .header-image {
            width: 100%;
            height: 200px; /* Ajusta la altura según tus necesidades */
            background-image: url("{{ url_for('static', filename='imagenes/imagen12.gif') }}");
            background-size: cover;
            background-position: center;
            clip-path: polygon(0 0, 100% 0, 100% 100%, 0 100%);
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .miDiv {
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            transition: transform 0.3s, box-shadow 0.3s;
            margin-top: -100px; /* Ajusta según la altura de la imagen */
            position: relative;
            z-index: 1;
        }

        .miDiv:hover {
            transform: scale(1.03);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
            color: #007bff;
        }

        .form-label {
            font-weight: bold;
            color: #333;
        }

        .cuadro {
            border-radius: 5px;
            border: 1px solid #ddd;
            padding: 8px;
        }

        .btn-primary {
            background-color: #0ccbdf;
            border-color: #0ccbdf;
            width: 100%;
            transition: background-color 0.3s, border-color 0.3s;
        }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }
    </style>
</head>

<body>
   
    <div class="container">
        
        <div class="miDiv">
            <h1>Crear Cuenta</h1>
            <div class="header-image"></div>
            <form action="{{ url_for('Clientes.add') }}" method="post">
                <div class="mb-3">
                    <label for="exampleInputNombreClientes" class="form-label">Nombre Clientes</label>
                    <input type="text" name="nombreClientes" class="form-control cuadro" id="exampleInputNombreClientes"
                        aria-describedby="nombreClientesHelp" required>
                </div>
                <div class="mb-3">
                    <label for="exampleInputDireccion1" class="form-label">Direccion Clientes</label>
                    <input type="text" name="direccionClientes" class="form-control cuadro" id="exampleInputDireccion1"
                        required>
                </div>
                <div class="mb-3">
                    <label for="exampleInputTelefono1" class="form-label">Telefono Clientes</label>
                    <input type="text" name="telefonoClientes" class="form-control cuadro" id="exampleInputTelefono1"
                        required>
                </div>
                <div class="mb-3">
                    <label for="exampleInputCorreo1" class="form-label">Correo Clientes</label>
                    <input type="email" name="correoClientes" class="form-control cuadro" id="exampleInputCorreo1"
                        required>
                </div>
                <div class="mb-3">
                    <label for="exampleInputContrasena1" class="form-label">Contrasena Clientes</label>
                    <input type="password" name="contrasenaClientes" class="form-control cuadro"
                        id="exampleInputContrasena1" required>
                </div>
                <button type="submit" class="btn btn-primary">Crear</button>
            </form>
        </div>
    </div>

</body>

</html>

app/templates/Clientes/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='styleClientes.css') }}">
  <script src="{{ url_for('static', filename='boot/js/bootstrap.js') }}"></script>
  <title>Editar Clientes</title>
</head>

<body>
  <div class="editar">
    <h1>Editar Clientes</h1>
    <form action="{{ url_for('Clientes.edit', idClientes=cliente.idClientes) }}" method="post">
      <div class="mb-3">
        <label for="exampleInputNombreClientes" class="form-label">Nombre Clientes</label>
        <input type="text" id="nombreClientes" name="nombreClientes" class="form-control"
          value="{{ cliente.nombreClientes }}" id="exampleInputNombreClientes" aria-describedby="nombreClientesHelp">
      </div>
      <div class="mb-3">
        <label for="exampleInputDireccion1" class="form-label">Direccion Clientes</label>
        <input type="text" id="direccionClientes" name="direccionClientes" class="form-control"
          value="{{ cliente.direccionClientes }}" id="exampleInputDireccion1">
      </div>
      <div class="mb-3">
        <label for="exampleInputTelefono1" class="form-label">Telefono Clientes</label>
        <input type="text" id="telefonoClientes" name="telefonoClientes" class="form-control"
          value="{{ cliente.telefonoClientes }}" id="exampleInputTelefono1">
      </div>
      <div class="mb-3">
        <label for="exampleInputCorreo1" class="form-label">Correo Clientes</label>
        <input type="text" id="correoClientes" name="correoClientes" class="form-control"
          value="{{ cliente.correoClientes }}" id="exampleInputCorreo1">
      </div>
      <div class="mb-3">
        <label for="exampleInputContrasena1" class="form-label">Contrasena Clientes</label>
        <input type="password" id="contrasenaClientes" name="contrasenaClientes" class="form-control"
          value="{{ cliente.contrasenaClientes }}" id="exampleInputContrasena1">
      </div>
      <button type="submit" class="btn btn-primary">Actualizar Cliente</button>
    </form>
  </div>
</body>

</html>

app/templates/Clientes/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="{{ url_for('static', filename='boot/js/jquery-3.7.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='boot/js/bootstrap.bundle.js') }}"></script>

    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 1200px;
            margin: auto;
            padding: 20px;
        }

        h1 {
            margin-bottom: 20px;
            color: #007bff;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #0ccbdf;
            color: #fff;
            font-weight: bold;
        }

        td {
            color: #333;
        }

        td a {
            color: #007bff;
            margin-right: 10px;
            transition: color 0.3s ease;
        }

        td a:hover {
            text-decoration: none;
            color: #0056b3;
        }

        .dropdown {
            display: inline-block;
            margin-bottom: 20px;
        }

        .dropdown-toggle {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
        }

        .dropdown-menu {
            min-width: 200px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .dropdown-item {
            color: #333;
            padding: 10px 20px;
            transition: background-color 0.3s ease;
        }

        .dropdown-item:hover {
            background-color: #0ccbdf;
            color: #fff;
        }
    </style>

    <title>Cliente</title>
</head>

<body>
    <div class="container">
        <h1>Lista de Clientes</h1>

        <div class="dropdown">
            <button class="btn btn-info dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Tablas
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{ url_for('Empleados.index') }}">Empleados</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Productos.index') }}">Productos</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Clientes.index') }}">Clientes</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Compras.index') }}">Compras</a></li>
                <li><a class="dropdown-item" href="{{ url_for('DetalleCompras.index') }}">DetalleCompras</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Ventas.index') }}">Ventas</a></li>
                <li><a class="dropdown-item" href="{{ url_for('DetalleVentas.index') }}">DetalleVentas</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Proveedores.index') }}">Proveedores</a></li>
                <li>
                    <form class="d-flex" role="searc
                    h" action="{{ url_for('Auth.logout') }}">
                        <button class="btn btn-outline-info" type="submit">Cerrar Sesión</button>
                    </form>
                </li>
            </ul>
        </div>

        <table>
            <tr>
                <th>Id Clientes</th>
                <th>Nombre Clientes</th>
                <th>Dirección Clientes</th>
                <th>Teléfono Clientes</th>
                <th>Correo Clientes</th>
                <th>Acciones</th>
            </tr>
            {% for Clientes in data %}
            <tr>
                <td>{{ Clientes.idClientes }}</td>
                <td>{{ Clientes.nombreClientes }}</td>
                <td>{{ Clientes.direccionClientes }}</td>
                <td>{{ Clientes.telefonoClientes }}</td>
                <td>{{ Clientes.correoClientes }}</td>
                <td>
                    <a href="{{ url_for('Clientes.edit', idClientes=Clientes.idClientes) }}">
                        <i class="bi bi-calendar-check"></i>
                    </a>
                    <a href="{{ url_for('Clientes.delete', idClientes=Clientes.idClientes) }}">
                        <i class="bi bi-trash3-fill"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</body>

</html>