app/models/Compras.py
from app import db


class Compras(db.Model):
    __tablename__ ='compra'
    idCompras = db.Column(db.Integer, primary_key=True)
    fechaCompras = db.Column(db.Date, nullable=False)
    cantidadCompras = db.Column(db.Integer, nullable=False)
    idProveedores = db.Column(db.Integer, db.ForeignKey('proveedor.idProveedores'))
    idEmpleados = db.Column(db.Integer, db.ForeignKey('empleado.idEmpleados'))
    

app/routes/Auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from app.models.Clientes import Clientes
from app.models.Empleados import Empleados

bp = Blueprint('Auth', __name__)
@bp.route('/', methods=['GET', 'POST'])
def login():
    global tipodeusuario
    if request.method == 'POST':
        nombre = request.form['nombre']
        contrasena = request.form['contrasena']
        
        empleados = Empleados.query.filter_by(nombreEmpleados=nombre, contrasenaEmpleados=contrasena).first()
    
        if empleados:
            login_user(empleados)
            flash("Login successful!", "success")
            tipodeusuario = 1
            print("Entra a empleado ", current_user.idEmpleados)
            return redirect(url_for('Empleados.index'))
        clientes = Clientes.query.filter_by(nombreClientes=nombre, contrasenaClientes=contrasena).first()

        if clientes:
            login_user(clientes)
            print(current_user.nombreClientes)            
            tipodeusuario = 0
            print("Entra a Cliente", current_user.idClientes)
            return redirect(url_for('Productos1.index'))
        flash('Invalid credentials. Please try again.','danger')
    return render_template("Auth/login.html")

@bp.route('/Iniciar')
@login_required
def Iniciar():
     return redirect(url_for('Productos1.index'))


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return render_template("Auth/login.html")

app/routes/Compras_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.Compras import Compras
from app import db

bp = Blueprint('Compras', __name__)

@bp.route('/Compras')
def index():
    data = Compras.query.all()
    # Compras_list = [Compras.to_dict() for book in data]
    # return jsonify(Compras_list)
    return render_template('Compras/index.html', data=data)

@bp.route('/Compras/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        fechaCompras = request.form['fechaCompras']
        cantidadCompras = request.form['cantidadCompras']
        idProveedores = request.form['idProveedores']
        idEmpleados = request.form['idEmpleados']

        new_Compras = Compras(fechaCompras=fechaCompras, cantidadCompras=cantidadCompras, idProveedores=idProveedores, idEmpleados=idEmpleados)
        db.session.add(new_Compras)
        db.session.commit()
        
        return redirect(url_for('Compras.index'))

    return render_template('Compras/add.html')

@bp.route('/Compras/edit/<int:idCompras>', methods=['GET', 'POST'])
def edit(idCompras):
    compra = Compras.query.get_or_404(idCompras)

    if request.method == 'POST':
        compra.fechaCompra = request.form['fechaCompras']
        compra.cantidadCompras = request.form['cantidadCompras']
        compra.idProveedores = request.form['idProveedores']
        compra.idEmpleados = request.form['idEmpleados']

        db.session.commit()
        return redirect(url_for('Compras.index'))

    return render_template('Compras/edit.html', compra=compra)
    

@bp.route('/Compras/delete/<int:idCompras>')
def delete(idCompras):
    compras = Compras.query.get_or_404(idCompras)
    
    db.session.delete(compras)
    db.session.commit()

    return redirect(url_for('Compras.index'))

app/templates/Compras/add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styleCompras.css') }}">
    <title>Agregar Compras</title>
</head>

<body>
    <h1>Agregar Compras</h1>
    <form action="{{ url_for('Compras.add') }}" method="post">
        <div class="mb-3">
            <label for="exampleInputFechaCompras" class="form-label">Fecha Compras</label>
            <input type="date" name="fechaCompras" class="form-control" id="exampleInputFechaCompras"
                aria-describedby="fechaComprasHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputCantidad1" class="form-label">Cantidad Compras</label>
            <input type="number" name="cantidadCompras" class="form-control" id="exampleInputCantidad1">
        </div>
        <div class="mb-3">
            <label for="exampleInputId1" class="form-label">Id Proveedores</label>
            <input type="number" name="idProveedores" class="form-control" id="exampleInputId1">
        </div>
        <div class="mb-3">
            <label for="exampleInputId1" class="form-label">Id Empleados</label>
            <input type="number" name="idEmpleados" class="form-control" id="exampleInputId1">
        </div>
        <button type="submit" class="btn btn-primary">Agregar Compra</button>
    </form>
</body>

</html>

app/templates/Compras/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='styleCompras.css') }}">
  <title>Editar Compras</title>
</head>

<body>
  <h1>Editar Compras</h1>
  <form action="{{ url_for('Compras.edit', idCompras=compra.idCompras) }}" method="post">
    <div class="mb-3">
      <label for="exampleInputFechaCompras" class="form-label">Fecha Compras</label>
      <input type="date" id="fechaCompras" name="fechaCompras" class="form-control" value="{{ compra.fechaCompras }}"
        id="exampleInputFechaCompras" aria-describedby="fechaComprasHelp">

    </div>
    <div class="mb-3">
      <label for="exampleInputCantidad1" class="form-label">Cantidad Compras</label>
      <input type="int" id="cantidadCompras" name="cantidadCompras" class="form-control"
        value="{{ compra.cantidadCompras }}" id="exampleInputCantidad1">
    </div>
    <div class="mb-3">
      <label for="exampleInputId1" class="form-label">Id Proveedores</label>
      <input type="int" id="idProveedores" name="idProveedores" class="form-control" value="{{ compra.idProveedores }}"
        id="exampleInputId1">
    </div>
    <div class="mb-3">
      <label for="exampleInputId1" class="form-label">Id Empleados</label>
      <input type="int" id="idEmpleados" name="idEmpleados" class="form-control" value="{{ compra.idEmpleados }}"
        id="exampleInputId1">
    </div>
    <button type="submit" class="btn btn-primary">Actualizar Compra</button>
  </form>
</body>

</html>

app/templates/Compras/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='boot/css/bootstrap.css') }}">
    <script src="{{ url_for('static', filename='boot/js/jquery-3.7.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='boot/js/bootstrap.bundle.js') }}"></script>
    <title>Compra</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 1200px;
            margin: auto;
            padding: 20px;
        }

        h1 {
            margin-bottom: 20px;
            color: #007bff;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #0ccbdf;
            color: #fff;
            font-weight: bold;
        }

        td {
            color: #333;
        }

        td a {
            color: #007bff;
            margin-right: 10px;
            transition: color 0.3s ease;
        }

        td a:hover {
            text-decoration: none;
            color: #0056b3;
        }

        .dropdown {
            display: inline-block;
            margin-bottom: 20px;
        }

        .dropdown-toggle {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
        }

        .dropdown-menu {
            min-width: 200px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .dropdown-item {
            color: #333;
            padding: 10px 20px;
            transition: background-color 0.3s ease;
        }

        .dropdown-item:hover {
            background-color: #0ccbdf;
            color: #fff;
        }
    </style>
</head>

<body>


    <div class="container">
        <h1>Lista de Compra</h1>
        <div class="dropdown">
            <button class="btn btn-info dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Tablas
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{ url_for('Empleados.index') }}">Empleados</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Productos.index') }}">Productos</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Clientes.index') }}">Clientes</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Compras.index') }}">Compras</a></li>
                <li><a class="dropdown-item" href="{{ url_for('DetalleCompras.index') }}">DetalleCompras</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Ventas.index') }}">Ventas</a></li>
                <li><a class="dropdown-item" href="{{ url_for('DetalleVentas.index') }}">DetalleVentas</a></li>
                <li><a class="dropdown-item" href="{{ url_for('Proveedores.index') }}">Proveedores</a></li>
                <li>
                    <form class="d-flex" role="search" action="{{ url_for('Auth.logout') }}">
                        <button class="btn btn-outline-info" type="submit">Cerrar Sesión</button>
                    </form>
                </li>
            </ul>
        </div>
        <table>
            <tr>
                <th>Id Compra</th>
                <th>Fecha Compras</th>
                <th>Cantidad Compras</th>
                <th>Id Proveedores</th>
                <th>Id Empleados</th>
                <th>Acciones</th>
            </tr>
            {% for Compras in data %}
            <tr>
                <td>{{ Compras.idCompras }}</td>
                <td>{{ Compras.fechaCompras }}</td>
                <td>{{ Compras.cantidadCompras }}</td>
                <td>{{ Compras.idProveedores }}</td>
                <td>{{ Compras.idEmpleados }}</td>
                <td>
                    <a href="{{ url_for('Compras.edit', idCompras=Compras.idCompras) }}"
                        class="btn btn-warning">Editar</a>
                    <a href="{{ url_for('Compras.delete', idCompras=Compras.idCompras) }}"
                        class="btn btn-danger">Eliminar</a>
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</body>

</html>